jdbc.url=jdbc:mysql://localhost:3306/bookstore_02?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false&allowPublicKeyRetrieval=true
jdbc.username=root
jdbc.password=Kha@01216114778
